version: '3'

services:
  # mongo for Andean
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./mongo:/data/db
  
  # postgres
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres:/var/lib/postgresql/data

  # redis
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379